version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nscore-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/src/nscore/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - /usr/src/nscore/nginx/sites:/etc/nginx/sites-enabled
#      - /usr/src/nscore/nginx/html:/usr/share/nginx/html  # Mapeo de la carpeta completa      
      - /usr/src/nscore/letsencrypt/www:/var/www/certbot:rw  # Para el reto HTTP-01
      - /etc/letsencrypt:/etc/letsencrypt  # Certificados generados
    restart: unless-stopped      
    depends_on:
      - nscore
    networks:
      - app-network
  nscore-python:
    build: 
      context: ./wwwroot/files/dockerPython
      dockerfile: Dockerfile
    image: nscore-python
    container_name: nscore-python
    volumes:
      - /usr/src/nscore/sqllite:/usr/src
      #- ./wwwroot/files/dockerPython:/app  # Mapea el código local al contenedor
    restart: unless-stopped
nscore:
    image: ghcr.io/nativosistemas/nscore:latest
    container_name: nscore
    restart: unless-stopped
    volumes:
      - /usr/src/nscore/sqllite:/usr/src
      - /usr/src/nscore/dotnet/appsettings.json:/App/appsettings.json
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: nscore-certbot
    volumes:
      - /usr/src/nscore/letsencrypt/www:/var/www/certbot:rw
      - /etc/letsencrypt:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c"
    command: |
      "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $!; done;"
    depends_on:
      - nginx
    restart: unless-stopped
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: nscore-duckdns
    env_file: /usr/src/nscore/duckdns/duckdns-secrets.env
    restart: always

networks:
  app-network:
    driver: bridge