version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - nscore
    networks:
      - app-network

  nscore:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nscore  
#    expose:
#      - "80"
    # expose no es necesario (Nginx accede vía red)
    environment:
      - ASPNETCORE_URLS=http://+:8080  # Fuerza a escuchar en 8080      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge