version: '3.8'

services:
  nginx:
    build: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/html:/usr/share/nginx/html  # Mapeo de la carpeta completa
    depends_on:
      - dotnetapp
    networks:
      - app-network

  dotnetapp:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge