version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nscore-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/src/nscore/nginx/nginx.conf:/etc/nginx/nginx.conf 
      - /usr/src/nscore/nginx/sites:/etc/nginx/sites-enabled
#      - shared-data:/usr/share/nginx/html  # Mapeo de la carpeta completa      
      - /usr/src/nscore/letsencrypt/www:/var/www/certbot:rw  # Para el reto HTTP-01
      - /etc/letsencrypt:/etc/letsencrypt  # Certificados generados
    restart: unless-stopped      
    depends_on:
      - nscore
      - nscore-seweb
    networks:
      - app-network
  nscore-nssky:
    image: ghcr.io/nativosistemas/nssky:latest
    pull_policy: always
    platform: linux/arm64
    container_name: nscore-nssky
    volumes:
      - /usr/src/nscore/sqllite:/usr/src
    restart: unless-stopped
  nscore:
    image: ghcr.io/nativosistemas/nscore:latest
    pull_policy: always
    platform: linux/arm64
    container_name: nscore
    restart: unless-stopped
    volumes:
      - /usr/src/nscore/sqllite:/usr/src
      - /usr/src/nscore/dotnet/appsettings.json:/App/appsettings.json
    networks:
      - app-network
  nscore-seweb:
    image: ghcr.io/nativosistemas/seweb:latest
    pull_policy: always
    platform: linux/arm64
    container_name: nscore-seweb
    restart: unless-stopped
#    volumes:
#      - shared-data:/usr/share/nginx/html
    networks:
      - app-network      
  certbot:
    image: certbot/certbot
    container_name: nscore-certbot
    volumes:
      - /usr/src/nscore/letsencrypt/www:/var/www/certbot:rw
      - /etc/letsencrypt:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c"
    command: |
      "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $!; done;"
    depends_on:
      - nginx
    restart: unless-stopped
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: nscore-duckdns
    env_file: /usr/src/nscore/duckdns/duckdns-secrets.env
    restart: always

networks:
  app-network:
    driver: bridge

#volumes:
#  shared-data:
