version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - nscore
    networks:
      - app-network

  nscore:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nscore  
    hostname: nscore  
    volumes:
      - /usr/src/dockerns:/usr/src
      - /usr/src/appsettings.json:/App/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:8080  # Fuerza a escuchar en 8080      
    networks:
      - app-network
  nscore-python:
    build: ./wwwroot/files/dockerPython
    image: nscore-python
    container_name: nscore-python
    hostname: nscore-python
    volumes:
      - /usr/src/dockerns:/usr/src
    restart: unless-stopped

networks:
  app-network:
    driver: bridge